version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: stajproje-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: irem123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - stajproje-network

  app:
    build: .
    container_name: stajproje-app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: irem123
    ports:
      - "8080:8080"
    networks:
      - stajproje-network

volumes:
  postgres_data:

networks:
  stajproje-network:
    driver: bridge
